services:
  pgsql:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=adminis
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
  minio_data:
